exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("olygold")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("olygold").insert([
        { team: "United States of America", gold: 39 },
        { team: "China", gold: 38 },
        { team: "Japan", gold: 27 },
        { team: "Great Britain", gold: 22 },
        { team: "ROC", gold: 20 },
        { team: "Australia", gold: 17 },
        { team: "Netherlands", gold: 10 },
        { team: "France", gold: 10 },
        { team: "Germany", gold: 10 },
        { team: "Italy", gold: 10 },
        { team: "Canada", gold: 7 },
        { team: "Brazil", gold: 7 },
        { team: "New Zealand", gold: 7 },
        { team: "Cuba", gold: 7 },
        { team: "Hungary", gold: 6 },
        { team: "Republic of Korea", gold: 6 },
        { team: "Poland", gold: 4 },
        { team: "Czech Republic", gold: 4 },
        { team: "Kenya", gold: 4 },
        { team: "Norway", gold: 4 },
        { team: "Jamaica", gold: 4 },
        { team: "Spain", gold: 3 },
        { team: "Sweden", gold: 3 },
        { team: "Switzerland", gold: 3 },
        { team: "Denmark", gold: 3 },
        { team: "Croatia", gold: 3 },
        { team: "Islamic Republic of Iran", gold: 3 },
        { team: "Serbia", gold: 3 },
        { team: "Belgium", gold: 3 },
        { team: "Bulgaria", gold: 3 },
        { team: "Slovenia", gold: 3 },
        { team: "Uzbekistan", gold: 3 },
        { team: "Georgia", gold: 2 },
        { team: "Chinese Taipei", gold: 2 },
        { team: "Turkey", gold: 2 },
        { team: "Greece", gold: 2 },
        { team: "Uganda", gold: 2 },
        { team: "Ecuador", gold: 2 },
        { team: "Ireland", gold: 2 },
        { team: "Israel", gold: 2 },
        { team: "Qatar", gold: 2 },
        { team: "Bahamas", gold: 2 },
        { team: "Kosovo", gold: 2 },
        { team: "Ukraine", gold: 1 },
        { team: "Belarus", gold: 1 },
        { team: "Romania", gold: 1 },
        { team: "Venezuela", gold: 1 },
        { team: "India", gold: 1 },
        { team: "Hong Kong, China", gold: 1 },
        { team: "Philippines", gold: 1 },
        { team: "Slovakia", gold: 1 },
        { team: "South Africa", gold: 1 },
        { team: "Austria", gold: 1 },
        { team: "Egypt", gold: 1 },
        { team: "Indonesia", gold: 1 },
        { team: "Ethiopia", gold: 1 },
        { team: "Portugal", gold: 1 },
        { team: "Tunisia", gold: 1 },
        { team: "Estonia", gold: 1 },
        { team: "Fiji", gold: 1 },
        { team: "Latvia", gold: 1 },
        { team: "Thailand", gold: 1 },
        { team: "Bermuda", gold: 1 },
        { team: "Morocco", gold: 1 },
        { team: "Puerto Rico", gold: 1 },
        { team: "Colombia", gold: 0 },
        { team: "Azerbaijan", gold: 0 },
        { team: "Dominican Republic", gold: 0 },
        { team: "Armenia", gold: 0 },
        { team: "Kyrgyzstan", gold: 0 },
        { team: "Mongolia", gold: 0 },
        { team: "Argentina", gold: 0 },
        { team: "San Marino", gold: 0 },
        { team: "Jordan", gold: 0 },
        { team: "Malaysia", gold: 0 },
        { team: "Nigeria", gold: 0 },
        { team: "Bahrain", gold: 0 },
        { team: "Saudi Arabia", gold: 0 },
        { team: "Lithuania", gold: 0 },
        { team: "North Macedonia", gold: 0 },
        { team: "Namibia", gold: 0 },
        { team: "Turkmenistan", gold: 0 },
        { team: "Kazakhstan", gold: 0 },
        { team: "Mexico", gold: 0 },
        { team: "Finland", gold: 0 },
        { team: "Botswana", gold: 0 },
        { team: "Burkina Faso", gold: 0 },
        { team: "C_te dIvoire", gold: 0 },
        { team: "Ghana", gold: 0 },
        { team: "Grenada", gold: 0 },
        { team: "Kuwait", gold: 0 },
        { team: "Republic of Moldova", gold: 0 },
        { team: "Syrian Arab Republic", gold: 0 }
      ]);
    });
};
